### ISSUE TITLE
Requires Xcode arguments

### ISSUE THREAD

**Issue by leogdion** [eneko/SourceDocs#63]
## Brief Description

Previously I could run
`swift run source-docs generate -c --spm-module OrchardNestKit`

However there appears to be a change which requires `<xcode-arguments>`

It seems either documentation should be updated or there's a bug. If I run:

`swift run sourcedocs generate build -c --spm-module OrchardNestKit`

The documentation works fine.

- **Operating System:** macOS 11
- **Xcode Version:** 12.0 beta 4
- **SwiftDocs Version/SHA:** ?
- **Swift version:** 5.3

## Demo Project

Check out CI error here:
https://github.com/brightdigit/OrchardNest/pull/61/checks?check_run_id=995029147

**Comment by eneko** [comment]
Thanks for raising this issue, @leogdion , I'm investigating it.

**Comment by eneko** [comment]
I'm not sure how Komondor works, I see the error when running `swift run sourcedocs generate --spm-module OrchardNestKit`. However, the SourceDocs executable is not part of your package, so not sure how `swift run` is finding it.

Running `sourcedocs generate --spm-module OrchardNestKit` (without `swift run`) it seems to work well.

I'd recommend installing SourceDocs with `brew install sourcedocs` in your CI script, instead of adding SourceDocs to your package.

**Comment by leogdion** [comment]
I'm just added `build` to my CI and that works fine for now.

My guess is that since the argument is assumed to be required when run through `swift run` as opposed to the standard way.
```
@Argument(help: "List of arguments to pass to xcodebuild")
    var xcodeArguments: [String]
```

This might be a bug in Swift Argument Parser or you could make `xcodeArguments` optional.

Thanks

**Comment by eneko** [comment]
@leogdion yeah, not sure what the issue is. Seems like a problem with using `swift run` on package dependencies, which I believe it is not officially supported. Komondor seems to use this "feature" but not sure that is a good idea.

`xcodeArguments` is not required, it can be empty. This is the case when running `sourcedocs` executable, but also when  using `swift run sourcedocs` if you clone this repository directly.

In any case, please feel free to open a PR if you figure it out.
